### PR TITLE
fix connector + azure

### PR DESCRIPTION
**Pull request by osheroff**
don't merge.  just showing where I'm at.

### CODE REVIEW

**Comment by osheroff** [comment]
ok @shyiko I've got a connection to Azure working.  This was a particularly tough one to solve, the code to respond to Azure's switch-auth message was simple enough, but if you look at my (admittedly hacked up) changes in `PacketChannel`, you'll see the artifact of a bizarre workaround; if we write just a single byte to azure (our length-of-packet byte), azure has troubles and immediately closes the connection.  If, on the other hand, we buffer our write and write out the whole packet at once (basically ensuring the packet doesn't fragment), everything is fine. 

I can make the code *much* cleaner but I thought I'd show you in code what I found.

**Comment by shyiko** [comment]
Great job, Ben! LGTM

**Comment by osheroff** [comment]
ok @shyiko this is ready to merge now

**Comment by shyiko** [comment]
:1st_place_medal:

**Comment by shyiko** [comment]
@osheroff 0.20.0 deployed to Maven Central

**Pull request merged**
