### PR TITLE
Backported v2

### PR DESCRIPTION
**Pull request by ghlogin**
1. fixes in readString for characters code exceeding a byte.

### CODE REVIEW

**Comment by shyiko** [comment]
Hi. What is your default charset? new String(byte[]) relies on platform charset for decoding to work properly. Also, if you have a test case (it doesn't have to be the real code even though it would certainly be more helpful if it was) I would really appreciate it. Thanks.

**Comment by ghlogin** [comment]
Hello,

the character set used is utf8_unicode_ci,
actually the issue was not character set , the underlying InputStream reads
in integer and then casts it to byte , apparently there is loss in
precision of character codes exceeding byte like 160 in my case which was
Non Breaking Space.

inside mysql table it looks like this :

+-------+------------------------+
| id    | site_name              |
+-------+------------------------+
| 81147 | dashstorenewyork.comÂ  |
+-------+------------------------+

doing ORD(RIGHT(dashstorenewyork.comÂ,1)) gives 160,

and binLogConnector gives it as dashstorenewyork.com(some diamond character
at the end).
after alot of debugging i found issue with underlying InputStream, so the
branch i uploaded
where i refactored readString which now casts interger to character, which
is solving my issue.

thank you for your reply,
please correct me if anywhere i have mistaken.

regards,
Shrishakti Mishra.

**Comment by shyiko** [comment]
Hi. I've updated few tests to demonstrate character set handling (see above). In short, everything works as expected provided the same charset is used (that is, for column definition and for new String(byte[], Charset)). Is your platform (system) encoding set to latin1 by any chance?

**Comment by shyiko** [comment]
Closed due to a lack of response.

**Pull request closed without merging**
