### PR TITLE
refact AbstractRowsDeserializer: make logic flow more reasonable

### PR DESCRIPTION
**Pull request by chenyun**

### CODE REVIEW

**Comment by chenyun** [comment]
Hi @shyiko , 
  I am not sure what's wrong with this pull request, why the Travis CI can't build?
  I just move the block of code to calc: typeCode, meta, length to an if block.
  If you found any problem with this pull request, please leave a comment,  I will fix it ASAP.

**Comment by shyiko** [comment]
Hi. 

Thanks for the PR. Regrading Travis CI build failure - if you click on :x: icon (next to commit message) you'll see

```
/home/travis/build/shyiko/mysql-binlog-connector-java/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AbstractRowsEventDataDeserializer.java:95: Line has trailing spaces.
```

Locally, you should get the same error when running `mvn checkstyle:check`.

Anyway, I'll gladly merge this in as soon as build passes.

**Comment by chenyun** [comment]
Thanks! I am newbie to Java, and really appreciate to your explanation. New skill got!

**Comment by shyiko** [comment]
Thank you :+1:

**Pull request merged**
