### PR TITLE
Support MariaDB GTID

### PR DESCRIPTION
**Pull request by wenerme**
#49

### CODE REVIEW

**Comment by wenerme** [comment]
The error is caused by checkstyle, my code style is different from the checkstyle.

**Comment by shyiko** [comment]
Hey @wener. Thank you for the contribution! I intend to merge this in but I'll have to squash and change quite a bit in order to keep backward compatibly and formatting / code style intact, first.

**Comment by wenerme** [comment]
That's ok, for backward compatibly may need expose gtidSet, but I think this added in recently, still can break now, consider a new release ?

**Comment by magicdoom** [comment]
@shyiko Can this merge please?  We need mariadb support

**Comment by magicdoom** [comment]
BinaryLogClient.java  1081 line:    if ("gtid_current_pos".equals(gtid) || "".equals(gtid)) {


should be      if ("gtid_current_pos".equals(gtid) || "".equals(gtid)||gtid==null) {


add a  "gtid==null" condition

**Comment by shyiko** [comment]
@magicdoom 

The only reason this hasn't been merged is a project scope widening. If I were to merge it I'd have to add MariaDB-specific tests (which this PR is missing), fix any critical MariaDB-specific issues (like https://github.com/shyiko/mysql-binlog-connector-java/issues/53) and more importantly be ready to provide basic user support. With the amount of free time I have I'd rather make sure that a few years from now this project is still going to be active. So you know, it basically comes down to a sustainability.

If you are willing to invest some of your time and create a MariaDB fork (say `mariadb-binlog-connector-java`) - I'd gladly add a link to it in readme.md.

**Comment by Trigl** [comment]
Do we support MariaDB gtid now? Or is there an available library to use?

**Pull request closed without merging**
