### PR TITLE
Atomic processing of create/remove of keepalive thread

### PR DESCRIPTION
**Pull request by jpechane**
When connect() and disconnect() are called concurrently it is possible that keepalive thread is not stopped because it is created only after it was attempted to be destoryed. This leads to a leaking keepalive thread that also keeps to create and maintain an undesirable connection.

This PR thus creates and destroys keepalive thread in a single atomic block which gurantees proper ordering and removes the race condition.

### CODE REVIEW

**Comment by shyiko** [comment]
Thank you, Jiri! 🙇

**Comment by gunnarmorling** [comment]
Hey @shyiko, thanks for the quick fix! Do you have any ETA for a new release containing this fix? We've seen multiple reports related to this recently by Debezium users, so we'd love to have a new version we could pull in.

**Comment by shyiko** [comment]
[0.19.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/CHANGELOG.md#0190---2019-02-13) uploaded to Maven Central.

**Comment by gunnarmorling** [comment]
Excellent, thank you so much! Pulling that in right away.

**Pull request merged**
